---
- name: Configure hosts & deploy application
  hosts: all
  become: true
  tasks:
    - name: Add an Apt signing key, uses whichever key is at the URL
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu xenial stable
        state: present
    - name: Install docker
      apt: name={{item}} state=installed
      with_items:
           - docker-ce
           - docker-compose
    - name: start docker
      service: name=docker state=started
    - name: create drectories
      file:
          path: "{{item}}"
          state: directory
          mode: 0755
      with_items:
           - /srv/gitlab/config
           - /srv/gitlab/data
           - /srv/gitlab/logs
