global:
  slack_api_url: 'https://hooks.slack.com/services/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'
  smtp_smarthost: 'smtp.mail.ru:465'
  smtp_from: 'apipil@mail.ru'
  smtp_auth_username: "apipil@mail.ru"
  smtp_auth_password: "password"
  smtp_require_tls: true

route:
  receiver: 'email-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#egor-panov'
- name: 'email-notifications'
  email_configs:
  - to: 'apipil@mail.ru'
