version: '3'
services:
  fluentd:
    env_file: .env
    build: ./fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      back_net:
      front_net:

  elasticsearch:
    env_file: .env
    image: elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      back_net:
      front_net:

  kibana:
    env_file: .env
    image: kibana
    ports:
      - "5601:5601"
    networks:
      back_net:
      front_net:

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      back_net:
      front_net:
networks:
  back_net:
  front_net:

