{
 "title": "UI_SERVICE_MONITORING",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "95% request time",
   "type": "graph",
   "description": "95 percentile response time on the ui query",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ui_request_latency_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "UI HTTP REQUESTS",
   "type": "graph",
   "description": "ALL HTTP requests that ui service received",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(ui_request_count[1m])" }
   ]
  },
  {
   "title": "ERROR UI requests",
   "type": "graph",
   "description": "All requests nah ui received with no-ok https codes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status =~ \"[45].*\"}[1m])"
    }
   ]
  }
 ]
}