groups:
  - name: alert.rules
    rules:
    - alert: InstanceDown
      expr: up == 0
      for: 1m
      labels:
        severity: page
      annotations:
        description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute'
        summary: 'Instance {{ $labels.instance }} down'
    - alert: Percentile95
      expr: histogram_quantile(0.95, sum(rate(ui_request_latency_seconds_bucket[1m])) by (le)) > 0.5
      for: 1m
      labels:
        severity: warning
      annotations:
        description: '{{ $labels.instance }} of job {{ $labels.job }} have percentile95 > 0.5 per minute'
        summary: 'Instance {{ $labels.instance }} have percentile95 > 0.5 per minute'